import type {
  ActionCaveat,
  AggregationResult,
  AutoGeneratedResult,
  CandidateResult,
  DataLimitation,
  GeneratedInsight,
  GeneratedNextActionPlan,
  GeneratedRecommendedAction,
  MissingDataRequest,
  ActionInsight,
  RankingResult,
  ReportBusinessType
} from "@/lib/report-generation/report-types";

type NextActionInput = {
  businessType?: ReportBusinessType;
  industry?: string;
  reportIntent?: string;
  keyFindings: GeneratedInsight[];
  businessRisks: CandidateResult[];
  growthOpportunities: CandidateResult[];
  dataLimitations: DataLimitation[];
  recommendedActions: GeneratedRecommendedAction[];
  aggregations: AggregationResult[];
};

const INDUSTRY_ACTION_RULES: Record<string, string[]> = {
  app_market: [
    "优化高安装低评分对象",
    "放大高评分低安装对象",
    "排查负向反馈集中的 App",
    "验证头部类别质量风险",
    "验证估算变现价值"
  ],
  ecommerce: ["放大高收入高利润产品", "优化高销售低利润产品", "排查高退款产品", "提升高流量低转化渠道"],
  saas: ["降低高 churn segment", "提升 trial-to-paid conversion", "放大高 LTV / 低 CAC 渠道"],
  marketing: ["增加高 ROAS 渠道预算", "降低低转化高成本渠道投入", "放大高转化低流量活动"],
  finance_timeseries: ["评估收益和回撤", "排查高波动周期", "分析异常成交量", "建立风险阈值"],
  operations: ["降低缺货风险", "处理滞销库存", "优化补货周期", "优化供应商表现"],
  inventory: ["降低缺货风险", "处理滞销库存", "优化补货周期", "降低库存占用"],
  customer_support: ["降低高频问题工单", "缩短高优先级工单处理时间", "提升低满意度问题类型"],
  product_usage: ["优化低使用高价值功能", "排查高流失路径", "提升活跃用户留存"],
  generic: ["处理高规模低质量对象", "放大高质量低规模对象", "补充真实收入、成本、时间或实体 ID"]
};

function allRankings(aggregations: AggregationResult[]) {
  return aggregations.flatMap((aggregation) => [
    ...aggregation.topRankings,
    ...aggregation.bottomRankings,
    ...aggregation.riskCandidates.flatMap((candidate) => candidate.affectedObjects?.length || candidate.objects?.length ? [] : []),
    ...aggregation.opportunityCandidates.flatMap((candidate) => candidate.targetObjects?.length || candidate.objects?.length ? [] : [])
  ]).filter((item): item is RankingResult => "rows" in item);
}

function objectName(row: Record<string, string | number | null>, index = 0) {
  return String(
    row.App ??
    row.Product ??
    row.product ??
    row.Category ??
    row.category ??
    row.dimension ??
    row.group ??
    row.Group ??
    `对象 ${index + 1}`
  );
}

function namesFromRows(rows?: Array<Record<string, string | number | null>>, count = 3) {
  return (rows ?? [])
    .slice(0, count)
    .map((row, index) => objectName(row, index))
    .filter(Boolean);
}

function bestRanking(aggregations: AggregationResult[], types: Array<NonNullable<RankingResult["rankingType"]>>) {
  const rankings = allRankings(aggregations);

  return types.flatMap((type) => rankings.filter((ranking) => ranking.rankingType === type))[0] ?? rankings[0];
}

function caveatType(limitation: DataLimitation): ActionCaveat["type"] {
  const text = `${limitation.id} ${limitation.title ?? ""} ${limitation.message}`.toLowerCase();
  if (text.includes("estimated") || text.includes("估算")) return "estimated_value";
  if (text.includes("dedup") || text.includes("去重") || text.includes("重复")) return "deduplication";
  if (text.includes("sample") || text.includes("样本")) return "small_sample";
  if (text.includes("time") || text.includes("趋势")) return "missing_trend";
  if (text.includes("benchmark") || text.includes("基准")) return "missing_benchmark";
  if (text.includes("raw") || text.includes("原始")) return "raw_metric";

  return "missing_field";
}

function limitationToCaveat(limitation: DataLimitation): ActionCaveat {
  const type = caveatType(limitation);

  return {
    id: `caveat-${limitation.id}`,
    type,
    message: limitation.limitation ?? limitation.message,
    affectedMetrics: limitation.title ? [limitation.title] : [],
    displayMode: type === "estimated_value" || type === "deduplication" ? "badge" : "collapsed_detail"
  };
}

function missingRequestFromLimitation(limitation: DataLimitation): MissingDataRequest | null {
  const text = `${limitation.id} ${limitation.title ?? ""} ${limitation.message} ${limitation.suggestedFix ?? ""}`.toLowerCase();

  if (text.includes("estimated") || text.includes("真实收入") || text.includes("paid_amount") || text.includes("order_amount")) {
    return {
      id: "missing-revenue-field",
      missingFieldType: "revenue",
      suggestedFields: ["paid_amount", "order_amount", "transaction_amount", "revenue", "cost", "ad_spend", "acquisition_cost"],
      whyNeeded: "当前估算价值只能用于方向判断，缺少真实收入和成本字段时无法验证 ROI / ROAS。",
      whatItEnables: "验证 Estimated Paid App Install Value，并计算真实 ROI / ROAS。",
      priority: "high"
    };
  }

  if (text.includes("cost") || text.includes("成本") || text.includes("roas") || text.includes("roi")) {
    return {
      id: "missing-cost-field",
      missingFieldType: "cost",
      suggestedFields: ["cost", "ad_spend", "cogs", "marketing_spend"],
      whyNeeded: "缺少成本字段时无法计算 ROI、利润率或预算效率。",
      whatItEnables: "判断是否应该加大投入、降本或重新分配预算。",
      priority: "high"
    };
  }

  if (text.includes("time") || text.includes("时间") || text.includes("trend") || text.includes("趋势")) {
    return {
      id: "missing-time-field",
      missingFieldType: "time",
      suggestedFields: ["date", "created_at", "timestamp", "order_date"],
      whyNeeded: "缺少时间字段时无法判断增长、下滑、周期波动或上次变化。",
      whatItEnables: "生成 current vs previous、rolling average 和趋势行动建议。",
      priority: "medium"
    };
  }

  if (text.includes("去重") || text.includes("dedup") || text.includes("实体")) {
    return {
      id: "missing-entity-id",
      missingFieldType: "entity_id",
      suggestedFields: ["app_id", "product_id", "sku", "customer_id"],
      whyNeeded: "缺少稳定实体 ID 时，重复名称可能放大总量和集中度判断。",
      whatItEnables: "生成去重规模指标和更可靠的 Top Share。",
      priority: "medium"
    };
  }

  if (text.includes("benchmark") || text.includes("目标") || text.includes("阈值") || text.includes("基准")) {
    return {
      id: "missing-benchmark",
      missingFieldType: "benchmark",
      suggestedFields: ["target", "baseline", "previous_period_value"],
      whyNeeded: "缺少业务目标或历史基准时，只能做方向性观察，不能判断是否达标。",
      whatItEnables: "判断高低、异常和行动优先级。",
      priority: "medium"
    };
  }

  return null;
}

function uniqueById<T extends { id: string }>(items: T[]) {
  const seen = new Set<string>();

  return items.filter((item) => {
    if (seen.has(item.id)) return false;
    seen.add(item.id);
    return true;
  });
}

function autoGeneratedResultsFromInput(input: NextActionInput): AutoGeneratedResult[] {
  const results: AutoGeneratedResult[] = [];
  const scaleRanking = bestRanking(input.aggregations, ["top_group", "top_by_scale"]);
  const riskRanking = bestRanking(input.aggregations, ["high_volume_low_quality", "bottom_by_quality"]);
  const opportunityRanking = bestRanking(input.aggregations, ["high_quality_low_volume", "top_group"]);
  const groupBy = input.aggregations.flatMap((aggregation) => aggregation.groupBys)[0];
  const trend = input.aggregations.flatMap((aggregation) => aggregation.timeTrends)[0];
  const distribution = input.aggregations.flatMap((aggregation) => aggregation.distributions)[0];

  if (scaleRanking?.rows.length) {
    const objects = namesFromRows(scaleRanking.rows);
    results.push({
      id: "auto-ranking-scale",
      title: "已识别头部规模对象",
      type: "ranking_analysis",
      resultSummary: `${objects.join("、")} 是当前规模靠前的对象或分组。`,
      keyObjects: objects,
      keyMetrics: [scaleRanking.metricField ?? scaleRanking.metric ?? scaleRanking.title],
      businessMeaning: "报告可以直接基于这些对象判断规模来源和头部集中风险，不需要用户再去查看排名。",
      sourceInsightIds: [scaleRanking.id]
    });
  }

  if (riskRanking?.rows.length) {
    const objects = namesFromRows(riskRanking.rows);
    results.push({
      id: "auto-risk-objects",
      title: "已识别风险候选对象",
      type: "risk_object_analysis",
      resultSummary: `${objects.join("、")} 已进入风险候选池。`,
      keyObjects: objects,
      keyMetrics: [riskRanking.metricField ?? riskRanking.metric ?? riskRanking.title],
      businessMeaning: "这些对象适合优先排查质量、负向反馈、转化或成本问题。",
      sourceInsightIds: [riskRanking.id]
    });
  }

  if (opportunityRanking?.rows.length) {
    const objects = namesFromRows(opportunityRanking.rows);
    results.push({
      id: "auto-opportunity-objects",
      title: "已识别机会候选对象",
      type: "opportunity_analysis",
      resultSummary: `${objects.join("、")} 可作为增长测试候选。`,
      keyObjects: objects,
      keyMetrics: [opportunityRanking.metricField ?? opportunityRanking.metric ?? opportunityRanking.title],
      businessMeaning: "这些对象或分组可以用于放大高质量低规模机会，或验证头部类别的增长空间。",
      sourceInsightIds: [opportunityRanking.id]
    });
  }

  if (groupBy) {
    results.push({
      id: "auto-group-analysis",
      title: "已完成分组聚合",
      type: "group_analysis",
      resultSummary: `系统已按 ${groupBy.dimension} 生成分组对比。`,
      keyObjects: namesFromRows(groupBy.rows),
      keyMetrics: groupBy.metrics,
      businessMeaning: "分组结果已经提供贡献来源、低表现分组和可放大细分市场的判断依据。",
      sourceInsightIds: [groupBy.id]
    });
  }

  if (trend) {
    results.push({
      id: "auto-trend-analysis",
      title: "已完成趋势聚合",
      type: "trend_analysis",
      resultSummary: `系统已按 ${trend.bucket} 生成 ${trend.metric} 趋势。`,
      keyObjects: [],
      keyMetrics: [trend.metric],
      businessMeaning: "趋势结果已经提供增长、下滑、周期波动或异常时间段的判断依据。",
      sourceInsightIds: [trend.id]
    });
  }

  if (distribution) {
    results.push({
      id: "auto-distribution-analysis",
      title: "已完成分布分析",
      type: "distribution_analysis",
      resultSummary: `${distribution.field} 已生成均值、中位数、分位数和极端值摘要。`,
      keyObjects: [],
      keyMetrics: [distribution.field],
      businessMeaning: "分布结果已经提供均值是否被头部对象拉高、是否存在长尾或极端值的判断依据。",
      sourceInsightIds: [distribution.id]
    });
  }

  return results.slice(0, 5);
}

function mapActionType(action: GeneratedRecommendedAction, businessType?: ReportBusinessType): ActionInsight["actionType"] {
  if (action.actionType === "create_deduped_metric" || action.actionType === "build_benchmark") {
    return "fix_data_quality_for_decision";
  }
  if (action.actionType === "collect_revenue_field") return "collect_missing_business_data";
  if (action.actionType) {
    return action.actionType as ActionInsight["actionType"];
  }

  const title = `${action.title} ${action.action} ${action.recommendedAction ?? ""}`;
  if (/负向|评论|反馈/.test(title)) return "reduce_negative_feedback";
  if (/机会|放大|增长/.test(title)) return "scale_opportunity_object";
  if (/ROI|收入|变现|估算/.test(title)) return "validate_roi";
  if (businessType === "finance_timeseries") return "investigate_anomaly";
  if (businessType === "marketing") return "reallocate_budget";
  if (businessType === "user_growth" || businessType === "product_usage") return "improve_retention";

  return "optimize_risk_object";
}

function normalizedActionText(text?: string) {
  return (text ?? "")
    .replace(/建议查看\s*Top\/Bottom\s*排名/g, "当前仅在已有 Top/Bottom 排名时呈现对象级结论")
    .replace(/建议查看/g, "当前基于已识别结果给出判断")
    .replace(/建议分析/g, "当前系统判断")
    .replace(/优先分析/g, "当前系统判断")
    .replace(/继续拆解/g, "当前缺少更细粒度证据，暂不作强结论")
    .replace(/补充分组对比/g, "当前缺少分组对比，暂不能定位分组来源")
    .replace(/补充时间对比/g, "当前缺少时间趋势，暂不能判断增长或下降")
    .replace(/修正规模指标口径/g, "当前规模口径存在限制，正式决策应使用可信口径")
    .replace(/\s+/g, " ")
    .trim();
}

function actionTitleFor(type: ActionInsight["actionType"], fallback: string) {
  if (type === "reduce_negative_feedback") return "排查负向反馈候选 App";
  if (type === "scale_opportunity_object") return "筛选头部类别中的高质量增长候选";
  if (type === "expand_high_performing_segment") return "筛选头部类别中的高质量增长候选";
  if (type === "validate_roi") return "验证估算价值是否能转化为真实收益";
  if (type === "reallocate_budget") return "将资源转向更高回报的对象或渠道";
  if (type === "improve_retention") return "提升关键用户群的留存表现";
  if (type === "reduce_cost") return "降低高成本低效率环节";
  if (type === "investigate_anomaly") return "排查已识别的异常变化";
  if (type === "fix_data_quality_for_decision") return "生成去重后的规模指标";
  if (type === "collect_missing_business_data") return /收入|revenue|paid_amount|order_amount|transaction_amount|cost|ad_spend|acquisition_cost/i.test(fallback)
    ? "补充真实收入和成本字段"
    : "补充关键业务字段";

  return fallback;
}

function evidenceText(action: GeneratedRecommendedAction) {
  const evidence = [
    ...(action.evidenceMetrics ?? []),
    ...(action.evidenceRankings ?? []),
    ...action.basedOn
  ].filter(Boolean);

  return Array.from(new Set(evidence)).slice(0, 4).join("、") || action.evidence || "系统已生成的结构化洞察";
}

function targetObjectText(objects: string[]) {
  return objects.length ? objects.slice(0, 4).join("、") : "当前已识别的重点对象";
}

function normalizeMetricKey(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function formatActionNumber(value: number, context = "") {
  if (!Number.isFinite(value)) return "";

  if (/rate|ratio|share|率|占比/i.test(context) && Math.abs(value) <= 1) {
    return `${(value * 100).toFixed(1)}%`;
  }

  const absolute = Math.abs(value);
  if (absolute >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(2)}B`;
  if (absolute >= 1_000_000) return `${(value / 1_000_000).toFixed(2)}M`;
  if (absolute >= 1_000) return `${(value / 1_000).toFixed(1)}K`;

  return Number.isInteger(value) ? String(value) : value.toFixed(2);
}

function formatActionValue(name: string, value: string | number | null | undefined) {
  if (value == null || value === "") return "";
  if (typeof value === "number") return formatActionNumber(value, name);

  return value;
}

function evidenceLookup(input: NextActionInput) {
  const values = new Map<string, string>();

  for (const insight of input.keyFindings) {
    for (const [key, value] of Object.entries(insight.evidenceValues ?? {})) {
      const formatted = formatActionValue(key, value);
      if (formatted) values.set(normalizeMetricKey(key), formatted);
    }
  }

  for (const risk of input.businessRisks) {
    for (const [key, value] of Object.entries(risk.evidenceValues ?? {})) {
      const formatted = formatActionValue(key, value);
      if (formatted) values.set(normalizeMetricKey(key), formatted);
    }
  }

  for (const opportunity of input.growthOpportunities) {
    for (const [key, value] of Object.entries(opportunity.evidenceValues ?? {})) {
      const formatted = formatActionValue(key, value);
      if (formatted) values.set(normalizeMetricKey(key), formatted);
    }
  }

  return values;
}

function findEvidenceValue(input: NextActionInput, names: string[]) {
  const lookup = evidenceLookup(input);

  for (const name of names) {
    const exact = lookup.get(normalizeMetricKey(name));
    if (exact) return exact;
  }

  for (const [key, value] of lookup) {
    if (names.some((name) => key.includes(normalizeMetricKey(name)))) return value;
  }

  return "";
}

function metricUnitLabel(metric = "") {
  if (/install/i.test(metric)) return "installs";
  if (/review/i.test(metric)) return "reviews";
  if (/volume/i.test(metric)) return "volume";

  return "";
}

function rowMetricValue(row: Record<string, string | number | null>, metric?: string) {
  if (metric && row[metric] != null) return row[metric];
  const candidates = ["value", "Installs", "installs", "Reviews", "reviews", "rating", "Rating", "score", "Score"];

  for (const key of candidates) {
    if (row[key] != null) return row[key];
  }

  return null;
}

function rankingEvidenceText(ranking?: RankingResult, count = 3) {
  if (!ranking?.rows.length) return "";

  const metric = ranking.metricField ?? ranking.metric ?? "";
  const unit = metricUnitLabel(metric);

  return ranking.rows.slice(0, count).map((row, index) => {
    const name = objectName(row, index);
    const value = formatActionValue(metric, rowMetricValue(row, metric));

    return value ? `${name}: ${value}${unit ? ` ${unit}` : ""}` : name;
  }).join("；");
}

function negativeActionEvidence(input: NextActionInput, risk: CandidateResult, objects: string[]) {
  const reviewVolume = findEvidenceValue(input, ["Review Volume", "Valid Review Volume"]);
  const negativeRate = findEvidenceValue(input, ["Negative Sentiment Rate"]);
  const sampleEvidence = sampleSizeEvidence(risk.affectedObjects ?? risk.objects);
  const parts = [
    reviewVolume ? `Review Volume = ${reviewVolume}` : "",
    negativeRate ? `整体 Negative Sentiment Rate = ${negativeRate}` : "",
    objects.length ? `对象级 ranking 识别出 ${objects.join("、")} 为负向反馈候选对象` : "",
    sampleEvidence ? `样本量：${sampleEvidence}` : ""
  ].filter(Boolean);

  return parts.join("；");
}

function headCategoryEvidence(input: NextActionInput, ranking?: RankingResult) {
  const rankingText = rankingEvidenceText(ranking, 3);
  if (rankingText) return rankingText;

  const installs = findEvidenceValue(input, ["Top Category by Installs", "Installs By Category"]);
  return installs ? `Top Category by Installs = ${installs}` : "";
}

function negativeExecution(objects: string[]) {
  const target = objects.length ? objects.join("、") : "负向反馈候选对象";

  return [
    `拉取 ${target} 的负向评论原文。`,
    "按功能缺陷、性能卡顿、广告体验、版本问题、价格/付费、兼容性分类。",
    "统计每类问题的出现次数和代表性评论。",
    "检查这些对象近期版本变化、评分变化和评论时间分布。",
    "输出 Top 3 负面问题主题和对应修复建议。"
  ];
}

function categoryQualityExecution(objects: string[]) {
  const target = objects.length ? objects.join("、") : "头部类别";

  return [
    `把 ${target} 与其他类别做对比表。`,
    "列出 installs、rating、review volume、negative sentiment rate。",
    "标记高安装低评分或高安装高负向反馈的类别。",
    "筛出需要优先排查的类别和对应 App。"
  ];
}

function categoryGrowthExecution(objects: string[]) {
  const target = objects.length ? objects.join("、") : "头部类别";

  return [
    `在 ${target} 中按明确条件筛选候选 App。`,
    "筛选条件：Rating 高于整体平均或 ≥ 4.5；Negative Sentiment Rate 低于整体平均；Installs 仍有提升空间；Reviews / Sentiment 样本量足够。",
    "为候选 App 设计 ASO、推荐位或投放测试方案。",
    "定义测试指标：安装量、评分、评论量、负向反馈率。",
    "输出增长实验候选清单和优先级。"
  ];
}

function dataExecutionFor(actionType: ActionInsight["actionType"]) {
  if (actionType === "collect_missing_business_data") {
    return [
      "补充 paid_amount、order_amount、transaction_amount、revenue、cost、ad_spend、acquisition_cost 字段。",
      "将真实收入和成本字段与 App、类别和时间维度关联。",
      "对比 Estimated Paid App Install Value 与真实收入。",
      "计算真实 ROI / ROAS 或变现优先级。"
    ];
  }

  return [
    "生成 Deduped Total Installs、Deduped Total Reviews、Deduped Top Share。",
    "与 Raw Total Installs、Raw Total Reviews、Raw Top Share 并列展示。",
    "标记原始口径和去重口径差异。",
    "输出 Raw vs Deduped 对比表。"
  ];
}

function executionForAction(actionType: ActionInsight["actionType"], objects: string[]) {
  if (actionType === "reduce_negative_feedback") return negativeExecution(objects);
  if (actionType === "expand_high_performing_segment") return categoryQualityExecution(objects);
  if (actionType === "scale_opportunity_object") return categoryGrowthExecution(objects);
  if (isDataActionType(actionType)) return dataExecutionFor(actionType);

  return [
    `把 ${targetObjectText(objects)} 整理成经营对象清单。`,
    "补充对应的规模、质量、转化或风险指标。",
    "按影响范围和可执行性排序，形成处理优先级。"
  ];
}

function deliverableFor(actionType: ActionInsight["actionType"]) {
  if (actionType === "reduce_negative_feedback") return "负向反馈问题清单 + Top 3 修复建议";
  if (actionType === "expand_high_performing_segment") return "头部类别质量风险对比表";
  if (actionType === "scale_opportunity_object") return "增长实验候选清单";
  if (actionType === "collect_missing_business_data") return "真实收入和成本字段映射表 + ROI / ROAS 验证结果";
  if (actionType === "fix_data_quality_for_decision") return "Raw vs Deduped 对比表";

  return "经营行动清单";
}

function rowSampleSize(row: Record<string, string | number | null>) {
  const value = row.sentimentSampleSize ?? row.sampleSize ?? row.sample_size ?? row.records ?? row.reviewCount ?? row.reviews;

  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function sampleSizeEvidence(rows?: Array<Record<string, string | number | null>>) {
  const samples = (rows ?? [])
    .slice(0, 3)
    .map((row, index) => {
      const sample = rowSampleSize(row);
      if (sample == null) return null;

      return `${objectName(row, index)}：${formatActionNumber(sample)} 条`;
    })
    .filter((value): value is string => Boolean(value));

  return samples.join("、");
}

function hasSmallSample(rows?: Array<Record<string, string | number | null>>) {
  return (rows ?? []).some((row) => {
    const sample = rowSampleSize(row);

    return sample != null && sample < 20;
  });
}

function isDataActionType(actionType?: ActionInsight["actionType"]) {
  return actionType === "fix_data_quality_for_decision" || actionType === "collect_missing_business_data";
}

function normalizedObjectKey(objects: string[]) {
  return objects
    .map((object) => object.toLowerCase().replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .sort()
    .slice(0, 4)
    .join("|");
}

function actionInsightScore(action: ActionInsight) {
  const priority = action.priority === "high" ? 30 : action.priority === "medium" ? 20 : 10;
  const business = isDataActionType(action.actionType) ? 0 : 25;
  const objects = action.targetObjects.length ? 10 : 0;
  const evidence = action.evidenceRankings.length * 5 + action.evidenceMetrics.length * 2;
  const confidence = Math.round(action.confidence * 10);

  return priority + business + objects + evidence + confidence;
}

function dedupeActionInsights(actions: ActionInsight[]) {
  const selected: ActionInsight[] = [];
  const seenIds = new Set<string>();
  const seenBusinessObjectGroups = new Set<string>();

  for (const action of [...actions].sort((left, right) => actionInsightScore(right) - actionInsightScore(left))) {
    if (seenIds.has(action.id)) continue;

    const isData = isDataActionType(action.actionType);
    const objectKey = normalizedObjectKey(action.targetObjects);
    const groupKey = !isData && objectKey ? `${action.actionType}:${objectKey}` : "";
    const similarExisting = !isData && selected.some((candidate) => {
      if (isDataActionType(candidate.actionType)) return false;
      if (candidate.actionType !== action.actionType) return false;

      const overlap = objectOverlapRatio(candidate.targetObjects, action.targetObjects);
      const sameEvidence = candidate.evidenceMetrics.some((metric) => action.evidenceMetrics.includes(metric));
      const sameImpact = candidate.expectedImpact === action.expectedImpact;

      return overlap > 0.5 || (sameEvidence && sameImpact);
    });

    if (groupKey && seenBusinessObjectGroups.has(groupKey)) continue;
    if (similarExisting) continue;

    seenIds.add(action.id);
    if (groupKey) seenBusinessObjectGroups.add(groupKey);
    selected.push(action);
  }

  return selected;
}

function objectOverlapRatio(left: string[], right: string[]) {
  const leftSet = new Set(left.map((item) => item.toLowerCase().trim()).filter(Boolean));
  const rightSet = new Set(right.map((item) => item.toLowerCase().trim()).filter(Boolean));
  if (!leftSet.size || !rightSet.size) return 0;

  let overlap = 0;
  for (const item of leftSet) {
    if (rightSet.has(item)) overlap += 1;
  }

  return overlap / Math.min(leftSet.size, rightSet.size);
}

function isHeadCategoryAction(action: ActionInsight) {
  const objectKey = normalizedObjectKey(action.targetObjects);

  return Boolean(objectKey) &&
    (action.actionType === "scale_opportunity_object" || action.actionType === "expand_high_performing_segment" || action.title.includes("高表现分组"));
}

function refineActionInsight(action: ActionInsight, input: NextActionInput): ActionInsight {
  if (action.actionType === "reduce_negative_feedback") {
    const reviewVolume = findEvidenceValue(input, ["Review Volume", "Valid Review Volume"]);
    const negativeRate = findEvidenceValue(input, ["Negative Sentiment Rate"]);
    const sampleEvidence = action.keyEvidence?.match(/样本量：[^；]+/)?.[0] ?? "";
    const keyEvidence = [
      reviewVolume ? `Review Volume = ${reviewVolume}` : "",
      negativeRate ? `整体 Negative Sentiment Rate = ${negativeRate}` : "",
      action.targetObjects.length ? `对象级 ranking 识别出 ${action.targetObjects.join("、")} 为负向反馈候选对象` : "",
      sampleEvidence
    ].filter(Boolean).join("；") || action.keyEvidence || action.evidence;

    return {
      ...action,
      title: "排查负向反馈候选 App",
      keyEvidence,
      recommendedAction: `当前只能识别 ${targetObjectText(action.targetObjects)} 为负向反馈候选对象；尚未生成评论主题聚类时，不能判断具体问题类型。`,
      executionSteps: negativeExecution(action.targetObjects),
      deliverable: deliverableFor("reduce_negative_feedback"),
      timeHorizon: "this_week",
      expectedImpact: "降低负向反馈对评分、留存和转化的影响。",
      caveat: action.caveat ?? "对象级负向率仅作为排查线索，不作为强风险结论；如样本量小于 20，请保留小样本线索判断。"
    };
  }

  if (input.businessType === "app_market" && isHeadCategoryAction(action)) {
    const ranking = bestRanking(input.aggregations, ["top_group", "top_by_scale"]);
    return {
      ...action,
      title: "筛选头部类别中的高质量增长候选",
      actionType: "scale_opportunity_object",
      keyEvidence: action.keyEvidence || headCategoryEvidence(input, ranking) || action.evidence,
      currentFinding: `${targetObjectText(action.targetObjects)} 是当前安装量或规模靠前的类别。`,
      businessMeaning: "这些头部类别已经具备流量基础，适合同时验证质量风险和增长机会。",
      recommendedAction: "筛选条件：Rating 高于整体平均或 ≥ 4.5；Negative Sentiment Rate 低于整体平均；Installs 仍有提升空间；Reviews / Sentiment 样本量足够。符合条件的 App 可进入 ASO、推荐位或投放测试候选池。",
      executionSteps: categoryGrowthExecution(action.targetObjects),
      deliverable: deliverableFor("scale_opportunity_object"),
      timeHorizon: "this_week",
      expectedImpact: "把头部类别的规模基础转化为可验证的增长实验。",
      caveat: action.caveat
    };
  }

  return action;
}

function actionScore(action: GeneratedRecommendedAction) {
  const priority = action.priority === "high" ? 30 : action.priority === "medium" ? 20 : 10;
  const business = action.type === "data_quality_action" ? 0 : 25;
  const objects = (action.targetObjects?.length ?? 0) * 4;
  const evidence = (action.evidenceRankings?.length ?? 0) * 5 + (action.evidenceMetrics?.length ?? 0) * 2;
  const caveatPenalty = Math.min(action.caveats?.length ?? 0, 3) * 2;

  return priority + business + objects + evidence - caveatPenalty;
}

function actionInsightsFromRecommended(input: NextActionInput): ActionInsight[] {
  const sorted = [...input.recommendedActions].sort((left, right) => actionScore(right) - actionScore(left));
  const businessActions = sorted.filter((action) => action.type !== "data_quality_action").slice(0, 5);
  const dataActions = sorted.filter((action) =>
    action.type === "data_quality_action" &&
    ((action.requiredDataIfAny?.length ?? 0) > 0 || action.actionType === "collect_revenue_field")
  ).slice(0, 3);

  return [...businessActions, ...dataActions].map((action) => {
    const actionType = mapActionType(action, input.businessType);
    const targetObjects = action.targetObjects ?? action.referencedObjects ?? [];
    const evidence = evidenceText(action);
    const recommendedAction = normalizedActionText(action.recommendedAction ?? action.action);
    const expectedImpact = normalizedActionText(action.expectedImpact ?? action.expectedOutcome);

    return {
      id: `next-${action.id}`,
      title: actionTitleFor(actionType, action.title),
      priority: action.priority,
      actionType,
      currentFinding: action.currentFinding ??
        (targetObjects.length
          ? `${targetObjectText(targetObjects)} 已被系统识别为本次报告的重点对象。`
          : "系统已经基于当前指标、风险、机会和聚合结果形成了可执行判断。"),
      evidence,
      keyEvidence: evidence,
      targetObjects,
      targetSegment: action.targetSegment,
      businessMeaning: action.whyItMatters ?? action.expectedImpact ?? action.expectedOutcome,
      recommendedAction,
      executionSteps: executionForAction(actionType, targetObjects),
      deliverable: deliverableFor(actionType),
      timeHorizon: isDataActionType(actionType) ? "this_month" : "this_week",
      expectedImpact,
      caveat: action.caveats?.[0],
      confidence: action.priority === "high" ? 0.84 : action.priority === "medium" ? 0.72 : 0.62,
      basedOn: action.basedOn,
      evidenceMetrics: action.evidenceMetrics ?? action.basedOn,
      evidenceRankings: action.evidenceRankings ?? []
    };
  });
}

function actionFromRisk(input: NextActionInput, risk: CandidateResult, index: number): ActionInsight {
  const objects = namesFromRows(risk.affectedObjects ?? risk.objects, 3);
  const objectSampleEvidence = sampleSizeEvidence(risk.affectedObjects ?? risk.objects);
  const isFeedback = /negative|sentiment|反馈|评论/i.test(`${risk.type} ${risk.title}`);
  const actionType: ActionInsight["actionType"] = isFeedback ? "reduce_negative_feedback" : "optimize_risk_object";
  const smallSample = isFeedback && hasSmallSample(risk.affectedObjects ?? risk.objects);
  const keyEvidence = isFeedback
    ? negativeActionEvidence(input, risk, objects)
    : [...risk.evidenceMetrics, risk.comparison].filter(Boolean).join("、");

  return {
    id: `next-risk-${risk.id || index}`,
    title: isFeedback ? "排查负向反馈候选 App" : "优先优化已识别的风险对象",
    priority: risk.severity === "high" ? "high" : risk.severity === "low" ? "low" : "medium",
    actionType,
    currentFinding: objects.length
      ? `${objects.join("、")} 已被识别为风险候选对象。`
      : risk.title,
    evidence: [...risk.evidenceMetrics, risk.comparison, objectSampleEvidence].filter(Boolean).join("、"),
    keyEvidence,
    targetObjects: objects,
    businessMeaning: risk.businessImpact ?? risk.businessMeaning,
    recommendedAction: isFeedback
      ? `当前只能识别 ${targetObjectText(objects)} 为负向反馈候选对象；尚未生成评论主题聚类时，不能判断具体问题类型。`
      : normalizedActionText(risk.recommendedAction),
    executionSteps: isFeedback ? negativeExecution(objects) : [
      `把 ${targetObjectText(objects)} 放入风险对象清单。`,
      "对比规模、质量、转化和反馈指标。",
      "列出影响最大的风险来源和处理优先级。"
    ],
    deliverable: isFeedback ? deliverableFor("reduce_negative_feedback") : "风险对象优化清单",
    timeHorizon: "this_week",
    expectedImpact: isFeedback
      ? "降低负向反馈对评分、留存和转化的影响。"
      : "优先处理高影响风险对象，降低其对整体经营表现的拖累。",
    caveat: smallSample
      ? "小样本线索：对象级负向率需结合评论样本量判断，不能单独作为强风险结论"
      : risk.confidence < 0.65 ? "证据置信度有限，建议结合样本量和对象级明细确认" : undefined,
    confidence: risk.confidence,
    basedOn: risk.evidenceMetrics,
    evidenceMetrics: risk.evidenceMetrics,
    evidenceRankings: []
  };
}

function actionFromOpportunity(opportunity: CandidateResult, index: number): ActionInsight {
  const objects = namesFromRows(opportunity.targetObjects ?? opportunity.objects, 3);

  return {
    id: `next-opportunity-${opportunity.id || index}`,
    title: objects.length ? "筛选头部类别中的高质量增长候选" : "验证已识别的增长机会",
    priority: opportunity.priority === "high" ? "high" : opportunity.priority === "low" ? "low" : "medium",
    actionType: "scale_opportunity_object",
    currentFinding: objects.length
      ? `${objects.join("、")} 已被识别为机会候选对象或分组。`
      : opportunity.title,
    evidence: [...opportunity.evidenceMetrics, opportunity.comparison].filter(Boolean).join("、"),
    keyEvidence: [...opportunity.evidenceMetrics, opportunity.comparison].filter(Boolean).join("、"),
    targetObjects: objects,
    businessMeaning: opportunity.businessMeaning,
    recommendedAction: objects.length
      ? "筛选条件：Rating 高于整体平均或 ≥ 4.5；Negative Sentiment Rate 低于整体平均；Installs 仍有提升空间；Reviews / Sentiment 样本量足够。符合条件的对象可进入 ASO、推荐位或投放测试候选池。"
      : normalizedActionText(opportunity.recommendedAction),
    executionSteps: objects.length ? categoryGrowthExecution(objects) : [
      "把当前机会候选对象整理成测试清单。",
      "为每个对象定义曝光、转化或满意度验证指标。",
      "执行小规模增长测试并比较测试前后结果。"
    ],
    deliverable: objects.length ? deliverableFor("scale_opportunity_object") : "增长机会验证清单",
    timeHorizon: "this_week",
    expectedImpact: objects.length
      ? "把头部类别的规模基础转化为可验证的增长实验。"
      : "把已有机会从分析结果转化为增长测试、资源倾斜或运营放大动作。",
    caveat: opportunity.confidence < 0.7 ? "当前机会证据为中等置信度，适合先做小规模验证" : undefined,
    confidence: opportunity.confidence,
    basedOn: opportunity.evidenceMetrics,
    evidenceMetrics: opportunity.evidenceMetrics,
    evidenceRankings: []
  };
}

function actionFromRanking(input: NextActionInput, autoGeneratedResults: AutoGeneratedResult[]): ActionInsight | null {
  const rankingResult = autoGeneratedResults.find((result) =>
    result.type === "ranking_analysis" ||
    result.type === "risk_object_analysis" ||
    result.type === "opportunity_analysis"
  );

  if (!rankingResult) return null;

  const isAppMarket = input.businessType === "app_market";
  const ranking = bestRanking(input.aggregations, ["top_group", "top_by_scale"]);
  const keyEvidence = isAppMarket ? headCategoryEvidence(input, ranking) : rankingResult.keyMetrics.join("、") || rankingResult.title;
  const actionType: ActionInsight["actionType"] = isAppMarket ? "expand_high_performing_segment" : rankingResult.type === "opportunity_analysis" ? "scale_opportunity_object" : "optimize_risk_object";

  return {
    id: "next-ranking-action",
    title: isAppMarket ? "验证头部类别是否伴随质量风险" : "把已识别头部对象转化为经营动作",
    priority: "medium",
    actionType,
    currentFinding: `${rankingResult.keyObjects.join("、")} 已经出现在系统自动分析结果中。`,
    evidence: rankingResult.keyMetrics.join("、") || rankingResult.title,
    keyEvidence,
    targetObjects: rankingResult.keyObjects,
    businessMeaning: rankingResult.businessMeaning,
    recommendedAction: isAppMarket
      ? `${targetObjectText(rankingResult.keyObjects)} 已被识别为头部规模来源；如果当前缺少同粒度质量聚合，暂不能判断是否存在高安装低质量类别。`
      : "这些对象已被系统识别为重点经营对象；若缺少同粒度质量、转化或风险聚合，暂不能进一步判定优化或放大方向。",
    executionSteps: isAppMarket ? categoryQualityExecution(rankingResult.keyObjects) : [
      `把 ${targetObjectText(rankingResult.keyObjects)} 整理成对象对比表。`,
      "补充规模、质量、转化和风险指标。",
      "将对象分为优化、放大和观察三类。"
    ],
    deliverable: isAppMarket ? deliverableFor("expand_high_performing_segment") : "对象经营动作清单",
    timeHorizon: "this_week",
    expectedImpact: isAppMarket
      ? "判断头部规模是否伴随质量风险。"
      : "让报告结果直接进入业务优化、资源分配和增长验证流程。",
    confidence: 0.72,
    basedOn: rankingResult.keyMetrics,
    evidenceMetrics: rankingResult.keyMetrics,
    evidenceRankings: [rankingResult.title]
  };
}

function fallbackAction(input: NextActionInput, autoGeneratedResults: AutoGeneratedResult[]): ActionInsight | null {
  const actionRules = INDUSTRY_ACTION_RULES[input.businessType ?? "generic"] ?? INDUSTRY_ACTION_RULES.generic;
  const evidenceMetrics = input.keyFindings.flatMap((finding) => finding.evidenceMetrics).slice(0, 3);
  const targetObjects = autoGeneratedResults.flatMap((result) => result.keyObjects).slice(0, 3);

  if (!evidenceMetrics.length && !targetObjects.length && !actionRules.length) return null;

  return {
    id: "next-generic-action",
    title: actionRules[0] ?? "把当前分析结果转化为下一步业务动作",
    priority: "medium",
    actionType: input.businessType === "finance_timeseries" ? "investigate_anomaly" : "optimize_risk_object",
    currentFinding: targetObjects.length
      ? `${targetObjects.join("、")} 是当前报告中最值得优先处理的对象。`
      : "系统已经生成了初步关键发现，但对象级证据仍有限。",
    evidence: evidenceMetrics.join("、") || "当前关键发现",
    keyEvidence: evidenceMetrics.join("、") || "当前关键发现",
    targetObjects,
    businessMeaning: "这一步用于把报告结论转成可以执行的经营动作，而不是停留在指标说明。",
    recommendedAction: "当前报告只形成了初步对象或指标证据，尚不足以给出更细的对象级业务结论。",
    executionSteps: [
      "选取当前证据最充分的对象或指标。",
      "定义一个可在一周内完成的小范围验证动作。",
      "记录执行前后的核心指标变化。"
    ],
    deliverable: "小范围业务验证记录",
    timeHorizon: "this_week",
    expectedImpact: "验证当前洞察是否能带来可观测的质量、增长、收入或效率改善。",
    confidence: targetObjects.length ? 0.66 : 0.55,
    basedOn: evidenceMetrics,
    evidenceMetrics,
    evidenceRankings: autoGeneratedResults.map((result) => result.title).slice(0, 2)
  };
}

export function generateNextActionPlan(input: NextActionInput): GeneratedNextActionPlan {
  const caveats = input.dataLimitations.map(limitationToCaveat);
  const missingDataRequests = uniqueById(input.dataLimitations.map(missingRequestFromLimitation).filter((item): item is MissingDataRequest => Boolean(item)));
  const autoGeneratedResults = autoGeneratedResultsFromInput(input);
  const actionCandidates = uniqueById([
    ...actionInsightsFromRecommended(input),
    ...input.businessRisks.slice(0, 2).map((risk, index) => actionFromRisk(input, risk, index)),
    ...input.growthOpportunities.slice(0, 2).map(actionFromOpportunity),
    actionFromRanking(input, autoGeneratedResults),
    fallbackAction(input, autoGeneratedResults)
  ].filter((item): item is ActionInsight => Boolean(item)));
  const dedupedActions = dedupeActionInsights(actionCandidates);
  const refinedActions = dedupeActionInsights(dedupedActions.map((action) => refineActionInsight(action, input)));
  const businessActions = refinedActions.filter((action) => !isDataActionType(action.actionType)).slice(0, 3);
  const dataActions = refinedActions.filter((action) => isDataActionType(action.actionType)).slice(0, 2);
  const actionInsights = [...businessActions, ...dataActions].slice(0, 5);

  return {
    autoGeneratedResults,
    actionInsights,
    priorityActions: actionInsights,
    missingDataRequests: missingDataRequests.slice(0, 5),
    caveats: caveats.slice(0, 8)
  };
}
