import assert from "node:assert/strict";
import fs from "node:fs";
import { join } from "node:path";
import test from "node:test";

test("report renderer is driven by decision_report props", () => {
  const source = fs.readFileSync(join(process.cwd(), "components/report-renderer-engine.tsx"), "utf8");

  assert.match(source, /type ReportRendererEngineProps/);
  assert.match(source, /report: DecisionIntelligenceReportV1 \| null/);
  assert.match(source, /Performance Overview/);
  assert.match(source, /SKU Breakdown/);
  assert.match(source, /Inventory Breakdown/);
  assert.match(source, /Inventory levels, sell-through, and stock coverage across SKUs/);
  assert.match(source, /Ads Breakdown/);
  assert.match(source, /Customer Intelligence Engine/);
  assert.match(source, /LTV Distribution/);
  assert.match(source, /Lifecycle Structure/);
  assert.match(source, /CustomerCohortTable/);
  assert.match(source, /CustomerSegmentTable/);
  assert.match(source, /SkuPortfolioOptimizationPanel/);
  assert.match(source, /AI SKU Decision Center/);
  assert.match(source, /SKU optimization decision/);
  assert.match(source, /Top Decisions/);
  assert.doesNotMatch(source, /AI模拟了/);
  assert.doesNotMatch(source, /Simulation 检测/);
  assert.doesNotMatch(source, /Simulation Check/);
  assert.doesNotMatch(source, /AI Profit Optimization/);
  assert.doesNotMatch(source, /Top AI Opportunities/);
  assert.doesNotMatch(source, /AI Recommended Portfolio/);
  assert.doesNotMatch(source, /AI Simulation Explorer/);
  assert.doesNotMatch(source, /AI Confidence/);
  assert.doesNotMatch(source, /当前没有可用于优化的 SKU 数据/);
  assert.match(source, /Current Plan/);
  assert.doesNotMatch(source, /Optimization Layer v2 Flow/);
  assert.doesNotMatch(source, /Optimization Layer v2 流程/);
  assert.doesNotMatch(source, /Profit Opportunity Summary/);
  assert.doesNotMatch(source, /利润机会摘要/);
  assert.doesNotMatch(source, /Expected vs Actual/);
  assert.doesNotMatch(source, /变化逻辑/);
  assert.doesNotMatch(source, /Feedback learning: waiting/);
  assert.doesNotMatch(source, /优先级/);
  assert.doesNotMatch(source, /当前状态/);
  assert.doesNotMatch(source, /AI建议动作/);
  assert.doesNotMatch(source, /为什么推荐/);
  assert.doesNotMatch(source, /模拟方案/);
  assert.doesNotMatch(source, /影响指标/);
  assert.doesNotMatch(source, /约束检查/);
  assert.match(source, /Profit Impact/);
  assert.match(source, /Why This Action/);
  assert.match(source, /DecisionDriversCell/);
  assert.match(source, /Why Scale/);
  assert.match(source, /Why Reduce \/ Stop/);
  assert.match(source, /Why Optimize/);
  assert.match(source, /buildFallbackDecisionDrivers/);
  assert.doesNotMatch(source, /Portfolio Actions/);
  assert.doesNotMatch(source, /PortfolioActionGroups/);
  assert.match(source, /Lifecycle/);
  assert.match(source, /Recommended Action/);
  assert.match(source, /RoleBadge/);
  assert.match(source, /skuRole/);
  assert.match(source, /recommendedActions/);
  assert.doesNotMatch(source, /保留 \/ 新增/);
  assert.doesNotMatch(source, /移出（共/);
  assert.doesNotMatch(source, /Added \/ Kept/);
  assert.doesNotMatch(source, /Removed \(/);
  assert.doesNotMatch(source, /Trade-off/);
  assert.match(source, /const selectedRows = useMemo/);
  assert.doesNotMatch(source, /recommended_portfolio\.slice\(0, 12\)/);
  assert.doesNotMatch(source, /显示 8/);
  assert.doesNotMatch(source, /showing 8/);
  assert.match(source, /DecisionBadge/);
  assert.match(source, /RecommendationStatusBadge/);
  assert.match(source, /Confidence/);
  assert.match(source, /Status/);
  assert.match(source, /Action Status/);
  assert.match(source, /Decision Status/);
  assert.match(source, /acceptDecisionAction/);
  assert.match(source, /rejectDecisionAction/);
  assert.match(source, /aria-pressed/);
  assert.doesNotMatch(source, /ScenarioExplorer/);
  assert.doesNotMatch(source, /<th className="px-3 py-3">\\{isZh \\? "Evidence"/);
  assert.match(source, /AI Scenario Comparison/);
  assert.match(source, /Simulation Breakdown/);
  assert.match(source, /AI Selected/);
  assert.match(source, /Action Outcome Tracker/);
  assert.match(source, /Accept/);
  assert.match(source, /Reject/);
  assert.match(source, /Details/);
  assert.match(source, /\/api\/actions\/accept/);
  assert.match(source, /\/api\/actions\/reject/);
  assert.match(source, /confidence_breakdown/);
  assert.match(source, /simulation_estimate/);
  assert.doesNotMatch(source, /xl:grid-cols-\[0\.95fr_1\.05fr\]/);
  assert.match(source, /lg:grid-cols-2/);
  assert.match(source, /function DetailSection/);
  assert.match(source, /break-words/);
  assert.match(source, /增加广告/);
  assert.doesNotMatch(source, /Profit Control Insight Engine/);
  assert.doesNotMatch(source, /ProfitControlInsightList/);
  assert.doesNotMatch(source, /DecisionIntelligenceV2Panel/);
  assert.doesNotMatch(source, /ActionRankingTable/);
  assert.doesNotMatch(source, /CounterfactualTable/);
  assert.doesNotMatch(source, /AutonomousCommerceRuntimePanel/);
  assert.doesNotMatch(source, /AutonomousExecutionQueue/);
  assert.doesNotMatch(source, /Autonomous Commerce Runtime/);
  assert.doesNotMatch(source, /Dry-run execution plan for SKU, Ads, Pricing, and Inventory optimization/);
  assert.doesNotMatch(source, /SkuOptimizationAlgorithmPanel/);
  assert.doesNotMatch(source, /SKU Profit Maximization Algorithm/);
  assert.doesNotMatch(source, /SkuBudgetAllocationTable/);
  assert.doesNotMatch(source, /SkuOptimizationRankTable/);
  assert.doesNotMatch(source, /LearningFeedbackPanel/);
  assert.doesNotMatch(source, /Action → Outcome → Learning Feedback Loop/);
  assert.match(source, /id="report-sku"/);
  assert.match(source, /id="report-ads"/);
  assert.match(source, /id="report-warehouse"/);
  assert.match(source, /id="report-customers"/);
  assert.doesNotMatch(source, /AI Insight Summary/);
  assert.match(source, /All channels/);
  assert.match(source, /channelTags/);
  assert.match(source, /function InventoryChart/);
  assert.match(source, /function InventoryTable/);
  assert.match(source, /buildInventoryRows/);
  assert.ok(source.indexOf("<InventoryChart rows={visibleInventoryRows} />") < source.indexOf("placeholder=\"Search SKU or product\""));
  assert.match(source, /Runway Days/);
  assert.match(source, /Sell-through Rate/);
  assert.match(source, /max-h-\[460px\] overflow-auto/);
  assert.match(source, /sticky top-0 z-10 bg-slate-50/);
  assert.doesNotMatch(source, /rows\.slice\(0, 12\)\.map/);
  assert.match(source, /product_name/);
  assert.match(source, /variant_name/);
  assert.match(source, /Size \{displayRow\.size\}/);
  assert.match(source, /displayProductName/);
  assert.match(source, /No product name/);
  assert.match(source, /`\$\{normalizedSku\}product`/);
  assert.doesNotMatch(source, /productName: row\.product_name \|\| row\.sku/);
  assert.match(source, /xl:grid-cols-7/);
  assert.match(source, /min-h-\[108px\]/);
  assert.match(source, /text-\[24px\]/);
  assert.match(source, /<span id="report-warehouse"/);
  assert.doesNotMatch(source, /min-w-0 truncate text-\[15px\] font-semibold text-slate-600/);
  assert.doesNotMatch(source, /Showing all available SKU rows/);
  assert.doesNotMatch(source, /Profit and margin are calculated/);
  assert.doesNotMatch(source, /经营分析报表|Decision Report JSON|decision_intelligence_v1/);
  assert.doesNotMatch(source, /DataQualityPanel|Metric confidence and coverage from the report payload/);
  assert.match(source, /fetch\s*\("\/api\/actions\/accept"/);
  assert.doesNotMatch(source, /computeCanonicalEcommerceMetrics|loadEcommerceSalesDashboardData|ShopifyGraphQL|GraphQL|access_token/);
});

test("dashboard report page exposes section navigation links", () => {
  const source = fs.readFileSync(join(process.cwd(), "components/dashboard.tsx"), "utf8");

  assert.match(source, /function ReportSectionNav/);
  assert.match(source, /#report-sku/);
  assert.match(source, /#report-ads/);
  assert.match(source, /#report-warehouse/);
  assert.match(source, /#report-customers/);
  assert.match(source, /报表板块导航|Report section navigation/);
  assert.match(source, /DecisionAnalysisEnginePanel/);
  assert.ok(source.indexOf("isAnalysisCacheMiss") < source.indexOf("<DecisionAnalysisEnginePanel"));
});

test("dashboard sidebar defaults collapsed with readable label layout", () => {
  const source = fs.readFileSync(join(process.cwd(), "components/dashboard.tsx"), "utf8");

  assert.match(source, /const \[isSidebarCollapsed, setIsSidebarCollapsed\] = useState\(true\)/);
  assert.match(source, /setIsSidebarCollapsed\(true\)/);
  assert.match(source, /writing-mode:horizontal-tb/);
  assert.doesNotMatch(source, /writing-mode:vertical-rl\] rotate-180/);
});

test("dashboard report page reads the ecommerce decision report endpoint", () => {
  const source = fs.readFileSync(join(process.cwd(), "components/dashboard.tsx"), "utf8");
  const reportPageStart = source.indexOf("function ReportPage(");
  const dashboardStart = source.indexOf("export function Dashboard(");
  const reportPageSource = source.slice(reportPageStart, dashboardStart);

  assert.match(reportPageSource, /\/api\/dashboard\/ecommerce\/report/);
  assert.match(reportPageSource, /<ReportRendererEngine/);
  assert.match(reportPageSource, /Date\.now\(\)/);
  assert.match(reportPageSource, /cache: "no-store"/);
  assert.doesNotMatch(source, /decisionReportPageDataCache/);
  assert.match(reportPageSource, /loadDecisionReport\(\)/);
  assert.match(reportPageSource, /isLoadingDecisionReport && !decisionReportPayload/);
});

test("decision report API reuses dashboard data loader and returns decision_report", () => {
  const source = fs.readFileSync(join(process.cwd(), "app/api/dashboard/ecommerce/decision-report/route.ts"), "utf8");
  const proxy = fs.readFileSync(join(process.cwd(), "proxy.ts"), "utf8");

  assert.match(source, /getCurrentWorkspaceContext/);
  assert.match(source, /findOptimizationReportCache/);
  assert.match(source, /findLatestDecisionSnapshot/);
  assert.match(source, /decisionSnapshotFreshness/);
  assert.match(source, /enqueueSkuOptimizationJob/);
  assert.match(source, /cachedOptimizationReportMissingOpsRows/);
  assert.match(source, /decision_report/);
  assert.doesNotMatch(source, /composeReport|computeCanonicalEcommerceMetrics|ShopifyGraphQL|GraphQL|access_token/);
  assert.match(proxy, /allowLocalDecisionReportFallback/);
  assert.match(proxy, /ENABLE_LOCAL_ARTIFACT_STORE/);
  assert.match(proxy, /\/api\/dashboard\/ecommerce\/decision-report/);
});

test("report renderer separates blended and attributed ROAS and avoids low-confidence inventory OK state", () => {
  const source = fs.readFileSync(join(process.cwd(), "components/report-renderer-engine.tsx"), "utf8");

  assert.match(source, /Blended MER/);
  assert.match(source, /Attributed ROAS/);
  assert.match(source, /Attribution unavailable/);
  assert.match(source, /ROAS unavailable: no campaign-level attribution data exists/);
  assert.match(source, /No campaign-level attribution data exists/);
  assert.match(source, /Normalized Daily Velocity/);
  assert.match(source, /30-day normalized estimate/);
  assert.match(source, /InventoryConfidenceBadge/);
  assert.match(source, /inventoryRiskStatusFromRow/);
  assert.match(source, /Inventory observation/);
  assert.match(source, /AI can decide/);
  assert.match(source, /LOW_CONFIDENCE_STOCK_RISK/);
  assert.match(source, /Stockout risk/);
  assert.match(source, /Potential excess inventory/);
  assert.match(source, /CAC attribution confidence insufficient/);
  assert.match(source, /Unavailable/);
  assert.match(source, /Campaign attribution unavailable when orders cannot be directly matched to campaigns/);
  assert.match(source, /Requires multiple customer cohorts/);
  assert.match(source, /Limited historical window/);
  assert.match(source, /insufficient cohort history/);
  assert.match(source, /Cohort analysis requires multiple customer cohorts/);
});
